### ISSUE TITLE
:warning: Warning issue

### ISSUE THREAD

**Issue by vladikoff** [vladikoff/Test#2]

**Comment by miketaylr** [comment]
:skull:

**Comment by vladikoff** [comment]
This issue is fairly old and there hasn't been much activity on it. Closing, but please re-open if it still occurs.
Not reproducible in the latest release. Please re-open this issue if it still occurs, with a JSBin containing a set of reproducible steps. Check this element's CONTRIBUTING.md for an example.
Please add a test case that tests the problem this PR is fixing.

aww yess https://chrome.google.com/webstore/detail/github-canned-responses/lhehmppafakahahobaibfcomknkhoina
